version: '3'

services:  
  mock-server:
    container_name: mock-server
    ports:
      - "9876:9876"
    build:
      context: .
      dockerfile: mock-server.Dockerfile

  pycontw-2021:
    build:
      context: .
      dockerfile: dev.Dockerfile
    ports:
      - "3000:3000"
